title: Carolina Dias
logo: "/images/bg.jpg"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Test Test Test
  <br><br>
  description
  <br><br>
  <a href="https://www.linkedin.com/in/carodias/">View My LinkedIn Profile</a> 
  
# theme: jekyll-theme-minimal
# google_analytics:  # your Google Analytics tracking ID here

plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton
